#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
# displays 4 and then "bad luck from China"
# displays 9 and then "bad luck from Japan"
# ddisplays 17 and then "bad luck from Italy"

count=1

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( count++ ))
done
